name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: python -m pip install -U jupyterlab~=3.1 jupyterlite==0.1.0b14 check-manifest

    - name: Build the extension
      run: |
        set -eux
        jlpm
        jlpm run eslint:check
        python -m pip install .
        jupyter labextension list 2>&1 | grep -ie "jupyterlite-ruby-kernel.*OK"

        # TODO: add JupyterLite browser check
        # python -m jupyterlab.browser_check

        # Install some extensions for demo
        jupyter labextension install plotlywidget
        jupyter lite build --output-dir dist --contents examples

        check-manifest -v

        pip install build
        python -m build --sdist
        cp dist/*.tar.gz myextension.tar.gz
        pip uninstall -y "jupyterlite-ruby-kernel" jupyterlab
        rm -rf myextension

    - uses: actions/upload-artifact@v2
      with:
        name: myextension-sdist
        path: myextension.tar.gz

    - uses: actions/upload-pages-artifact@v1
      with:
        path: ./dist

  test_isolated:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - uses: actions/download-artifact@v2
      with:
        name: myextension-sdist
    - name: Install and Test
      run: |
        set -eux
        # Remove NodeJS, twice to take care of system and locally installed node versions.
        sudo rm -rf $(which node)
        sudo rm -rf $(which node)
        pip install myextension.tar.gz
        pip install jupyterlab
        jupyter labextension list 2>&1 | grep -ie "jupyterlite-ruby-kernel.*OK"

        # TODO: add JupyterLite browser check
        # python -m jupyterlab.browser_check --no-chrome-test

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
